name: 'Setup git-crypt'
description: 'Setup git-crypt for use in github actions.'
author: 'Flydiverny'
branding:
  icon: unlock
  color: purple
inputs:
  version:
    required: false
    description: 'git-crypt version'
    default: '0.7.0'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/post/index.js'
  post-if: always()
